version: '3.8'

services:
  comp20081:
    container_name: comp20081
    build: .
    depends_on:
      - load_balancer
    networks:
      - backend
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-password
      MYSQL_HOST: mysql
    volumes:
      - ./app:/app
    command: ["java", "-jar", "COMP20081.jar"]

  load_balancer:
    container_name: load_balancer
    build: ./load_balancer
    depends_on:
      - mysql
      - file_server1
      - file_server2
      - file_server3
      - file_server4
    networks:
      - backend
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-password
      MYSQL_HOST: mysql

  file_server1:
    container_name: file_server1
    build: ./file_server
    networks:
      - backend
    volumes:
      - file_data1:/data

  file_server2:
    container_name: file_server2
    build: ./file_server
    networks:
      - backend
    volumes:
      - file_data2:/data

  file_server3:
    container_name: file_server3
    build: ./file_server
    networks:
      - backend
    volumes:
      - file_data3:/data

  file_server4:
    container_name: file_server4
    build: ./file_server
    networks:
      - backend
    volumes:
      - file_data4:/data

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: comp20081
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:
  file_data1:
  file_data2:
  file_data3:
  file_data4:

networks:
  backend:
