
services:
  main-container:
    container_name: comp20081-main
    image: pedrombmachado/ntu_lubuntu:comp20081
    ports:
      - "3390:3389"
      - "2022:22" 
    volumes:
      - main_data:/home/ntu-user/NetBeansProjects
    environment:
      - DISPLAY=:0
    networks:
      - comp20081_network

  load-balancer:
    container_name: comp20081-loadbalancer
    image: pedrombmachado/ntu_lubuntu:comp20081
    ports:
      - "4847:22"
    depends_on:
      - lamp-server
    networks:
      - comp20081_network

  file-server1:
    container_name: comp20081-files1
    image: pedrombmachado/simple-ssh-container:base
    environment:
      - ROOT_PASSWORD=root
    command: sh -c "echo 'root:root' | chpasswd && /usr/sbin/sshd -D"
    ports:
      - "4848:22"
    volumes:
      - files1_data:/storage
    networks:
      - comp20081_network

      
  file-server2:
    container_name: comp20081-files2
    image: pedrombmachado/simple-ssh-container:base
    environment:
      - ROOT_PASSWORD=root
    command: sh -c "echo 'root:root' | chpasswd && /usr/sbin/sshd -D"
    ports:
      - "4849:22"
    volumes:
      - files2_data:/storage  
    networks:
      - comp20081_network

  file-server3:
    container_name: comp20081-files3
    image: pedrombmachado/simple-ssh-container:base
    environment:
      - ROOT_PASSWORD=root
    command: sh -c "echo 'root:root' | chpasswd && /usr/sbin/sshd -D"
    ports:
      - "4850:22"
    volumes:
      - files3_data:/storage
    networks:
      - comp20081_network

  file-server4:
    container_name: comp20081-files4
    image: pedrombmachado/simple-ssh-container:base
    environment:
      - ROOT_PASSWORD=root
    command: sh -c "echo 'root:root' | chpasswd && /usr/sbin/sshd -D"
    ports:
      - "4851:22"
    volumes:
      - files4_data:/storage
    networks:
      - comp20081_network

  lamp-server:
    container_name: comp20081-lamp
    image: mattrayner/lamp:latest-1804
    ports:
      - "8080:80"    # Apache Web Server
      - "3306:3306"  # MySQL Server
    volumes:
      - lamp_data:/app    # Persistent storage for Apache
      - ./mysql:/var/lib/mysql  # ✅ Persistent MySQL storage using local `mysql/` folder
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: hFmMBpg8952e
      MYSQL_DATABASE: comp20081
    networks:
      - comp20081_network

volumes:
  main_data:
  files1_data:
  files2_data:
  files3_data:
  files4_data:
  lamp_data:

networks:
  comp20081_network:
